# Generated by Django 6.0.1 on 2026-01-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideradar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_payment_method',
            field=models.CharField(choices=[('onapp', 'On App'), ('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card')], default='cash', max_length=20),
        ),
    ]
